[project]
name = "love-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.0",
    "flask-wtf>=1.0.0",
    "moviepy>=2.2.1",
    "pillow>=8.0.0",
]
